{{- if .Values.persistence.owncloud.nfs.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "owncloud.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  nfs:
    server: {{ .Values.persistence.owncloud.nfs.server }}
    path: {{ .Values.persistence.owncloud.nfs.path }}
{{end}}
---
{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "owncloud.fullname" . }}
spec:
  accessModes:
    - {{ .Values.persistence.owncloud.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.owncloud.size }}
  storageClassName: {{ .Values.persistence.owncloud.storageClassName }}
{{- end -}}